services:
  docs:
    image: iacpaas_materials_local_docs
    container_name: iacpaas_materials_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./iacpaas_materials:/app/iacpaas_materials:z
    ports:
      - '9000:9000'
    command: /start-docs
